# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sprout < Formula
  desc "Git worktree manager with terminal UI and tmux workflows."
  homepage "https://github.com/joegrabski/sprout"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.3/sprout_0.1.3_darwin_amd64.tar.gz"
      sha256 "d5a97e66e29f47244179d64db9d0ec13ac2ff985870887d6107463760f028c93"

      def install
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.3/sprout_0.1.3_darwin_arm64.tar.gz"
      sha256 "692123f62328e4f3d5ea1b8a40424881ede3ed5bcc6fa60e201d08ee5540e491"

      def install
        bin.install "sprout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.3/sprout_0.1.3_linux_amd64.tar.gz"
      sha256 "8d798c958b700a5521be33b49a4b47ac1407f5a0a5ddf3010fa82233adea3afd"
      def install
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.3/sprout_0.1.3_linux_arm64.tar.gz"
      sha256 "c68a0e9d61ab23797843c37305279a7545e9323a7636902c44c427bbb529f550"
      def install
        bin.install "sprout"
      end
    end
  end

  test do
    system "#{bin}/sprout", "version"
  end
end
