# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sprout < Formula
  desc "Git worktree manager with terminal UI and tmux workflows."
  homepage "https://github.com/joegrabski/sprout"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.5/sprout_0.1.5_darwin_amd64.tar.gz"
      sha256 "e0fecb6ac134733a5050851dabbd5d2bcdd53f7b7f61b0b3b8eb3ce4a0e25d58"

      def install
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.5/sprout_0.1.5_darwin_arm64.tar.gz"
      sha256 "8fe3aae66c1dd41d30b3e158ab683256a67e69f001d3764314224c278df676f7"

      def install
        bin.install "sprout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.5/sprout_0.1.5_linux_amd64.tar.gz"
      sha256 "b63499f0835ae7cb761e164a7c88ff74065f242e4eed13b4c942d81e15b82ce4"
      def install
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.5/sprout_0.1.5_linux_arm64.tar.gz"
      sha256 "4434505a645c23a10a86e26a87ffda43fa62fb24766f683f7d841b32f1308ac7"
      def install
        bin.install "sprout"
      end
    end
  end

  test do
    system "#{bin}/sprout", "version"
  end
end
