# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sprout < Formula
  desc "Git worktree manager with terminal UI and tmux workflows."
  homepage "https://github.com/joegrabski/sprout"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.4/sprout_0.1.4_darwin_amd64.tar.gz"
      sha256 "664f8ccafec68c730c8686645cbc70e8f99801b2808b9a1d4eb13b6033b055ae"

      def install
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.4/sprout_0.1.4_darwin_arm64.tar.gz"
      sha256 "8187e75d8097b39dc11c16c27eba892cbf44a6adc466147736af974d8f7bcc8f"

      def install
        bin.install "sprout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.4/sprout_0.1.4_linux_amd64.tar.gz"
      sha256 "873cf2c3426e6f9a9deb7fb9e554c14ebf536d083b50211d4785aa9223d6a537"
      def install
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.4/sprout_0.1.4_linux_arm64.tar.gz"
      sha256 "23b78cbc271f79a171895e773621d97d4384644a43ef4f224d45c3629a449adf"
      def install
        bin.install "sprout"
      end
    end
  end

  test do
    system "#{bin}/sprout", "version"
  end
end
